[repository]
name = "hyprland-modmove"
authors = ["keith"]
commit_pins = [
  ["39d7e209c79d451efab1b21151d5938289da838d", "f40ab8f3a98e861306d6ffdcc6c64e313a6582dd"],
]

[modmove]
description = "Move and resize floating windows by holding modifiers and moving the cursor"
authors = ["keith"]
output = "modmove.so"
build = [
  "make all",
]
